[package]
name = "skyscanner"
version = "0.1.0"
edition = "2021"
authors = ["boris.lok <boris.lok.tw@outlook.com>"]


[dependencies]
reqwest = { version = "0.11.14", features = ["json", "serde_json"] }
